export enum dbType {
  Mysql = 'mysql',
  Mariadb = 'mariadb',
  Postgres = 'postgres',
  Cockroachdb = 'cockroachdb',
  Sqlite = 'sqlite',
  Mssql = 'mssql',
  Sap = 'sap',
  Oracle = 'oracle',
  Cordova = 'cordova',
  Nativescript = 'nativescript',
  ReactNative = 'react-native',
  Sqljs = 'sqljs',
  Mongodb = 'mongodb',
  AuroraDataApi = 'aurora-data-api',
  AuroraDataApiPg = 'aurora-data-api-pg',
  Expo = 'expo',
  BetterSqlite3 = 'better-sqlite3',
  Capacitor = 'capacitor',
}
